[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_flags =
   -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	m5stack/M5Unified@^0.2.17
	m5stack/M5Cardputer@^1.1.1
	m5stack/M5GFX@^0.2.24
	arduino-libraries/NTPClient@^3.2.1
	m5stack/M5Unit-RTC@^0.1.0
	lucadentella/TOTP library@^1.1.0
