// English
#ifdef lang_en
#define PASSWORD_MANAGER_TITLEBAR "Passwords"
#define LOGIN_TITLEBAR "Enter password"
#define HANDBOOK_TITLEBAR "Help"
#define OPTIONS_TITLEBAR "Options"
#define SYNC_TITLEBAR "Synchronization"
#define CREDITS_TITLEBAR "Credits"
#define PWIMPORT_TITLEBAR "New passwords found"
#define SEARCH_TITLEBAR "Search"

#define HANDBOOK_KEY_HELP "H - help"
#define HANDBOOK_KEY_BACK "< (,) - back"
#define HANDBOOK_KEY_EXIT "Esc (`) - exit"
#define HANDBOOK_KEY_FORWARD "> (/) - forward"
#define HANDBOOK_KEY_USERNAME "1 - username input"
#define HANDBOOK_KEY_PASSWORD "2 - password input"
#define HANDBOOK_KEY_FULLINPUT "3 - full input"
#define HANDBOOK_KEY_TOTPINPUT "4 - TOTP input"
#define HANDBOOK_KEY_DEFAULTINPUT "OK - default input"
#define HANDBOOK_KEY_TAB "T - hit TAB"
#define HANDBOOK_KEY_ENTER "R - hit ENTER"
#define HANDBOOK_KEY_PREVIEW "V - preview"
#define HANDBOOK_KEY_LOCK "L - lock"
#define HANDBOOK_KEY_MUTE "M - mute"
#define HANDBOOK_KEY_OPTIONS "O - options"
#define HANDBOOK_KEY_SYNC "S - sync"
#define HANDBOOK_KEY_CREDITS "C - credits"
#define HANDBOOK_KEY_RECONNECT "N - connect Wi-Fi"

#define OPTIONS_DEFAULT_USERNAME "Default input mode: username"
#define OPTIONS_DEFAULT_PASSWORD "Default input mode: password"
#define OPTIONS_DEFAULT_FULL "Default input mode: full"
#define OPTIONS_SSID "Wi-Fi SSID: "
#define OPTIONS_WIFI_PASSWORD "Wi-Fi Key: "
#define OPTIONS_SYNC_HOST "Sync host: "
#define OPTIONS_SYNC_PORT "Sync port: "
#define OPTIONS_DEVICE_PASSWORD "Password: "
#define OPTIONS_WIFI_OFF "Wi-Fi timeout: Wi-Fi Off"
#define OPTIONS_WIFI_TIMEOUT "Wi-Fi timeout: "
#define OPTIONS_WIFI_TIMEOUT_SECONDS_SHORTCUT " s"
#define OPTIONS_RTC_TIME "RTC Time: "
#define OPTIONS_RTC_NTPSYNC " | Sync w/ NTP"
#define OPTIONS_RTC_NTPSYNC_RTC_UNAVAILABLE "Sync unavailable: No RTC"
#define OPTIONS_EXPORT_VAULT "ENTER to export vault to SD"

#define SYNC_WIFI_CONNECTING_PHASE "Connecting to Wi-Fi"
#define SYNC_SERVER_CONNECTING_PHASE "Connecting to server"
#define SYNC_DOWNLOAD_PHASE "Downloading data"
#define SYNC_OK "Sync OK, disconnecting"
#define SYNC_RETURN "Returning in 3 seconds"
#define SYNC_ERR "Sync error:"
#define SYNC_ERR_DESCRIPTION_WIFI "Wi-Fi error"
#define SYNC_ERR_DESCRIPTION_SERVER "Server error"
#define SYNC_ERR_DESCRIPTION_FILE "File error"

#define CREDITS_PWDER "PWDer 0.5 \"Untangled\" >"
#define CREDITS_WEBSITE "< Visit my website!"
#define CREDITS_PWDER_GITHUB "adamecki/PWDer on GitHub"
#define CREDITS_WEBSITE_LINK "floriano.uk"

#define PWIMPORT_REPLACE_PASSWORDS "Replace current passwords?"

#define SEARCH_NO_RESULTS "No results"

#define SDCARD_NOT_FOUND_TITLE "Error"
#define SDCARD_NOT_FOUND_DESCRIPTION "SD card not found!"

#define SAMPLE_ENTRY "Sample Entry"
#define SAMPLE_USERNAME "sample_user"
#define SAMPLE_PASSWORD "sample_password"
#endif

// Polish
#ifdef lang_pl
#define PASSWORD_MANAGER_TITLEBAR "Moje hasla"
#define LOGIN_TITLEBAR "Podaj haslo"
#define HANDBOOK_TITLEBAR "Pomoc"
#define OPTIONS_TITLEBAR "Opcje"
#define SYNC_TITLEBAR "Synchronizacja"
#define CREDITS_TITLEBAR "O programie"
#define PWIMPORT_TITLEBAR "Znaleziono nowe hasla"
#define SEARCH_TITLEBAR "Wyszukaj"

#define HANDBOOK_KEY_HELP "H - pomoc"
#define HANDBOOK_KEY_BACK "< (,) - wstecz"
#define HANDBOOK_KEY_EXIT "Esc (`) - wyjdz"
#define HANDBOOK_KEY_FORWARD "> (/) - naprzod"
#define HANDBOOK_KEY_USERNAME "1 - wpisz nazwe uzytkownika"
#define HANDBOOK_KEY_PASSWORD "2 - wpisz haslo"
#define HANDBOOK_KEY_FULLINPUT "3 - wpisz wszystko"
#define HANDBOOK_KEY_TOTPINPUT "4 - wpisz TOTP"
#define HANDBOOK_KEY_DEFAULTINPUT "OK - wpisz wg domyslnej opcji"
#define HANDBOOK_KEY_TAB "T - wcisnij TAB"
#define HANDBOOK_KEY_ENTER "R - wcisnij ENTER"
#define HANDBOOK_KEY_PREVIEW "V - podglad"
#define HANDBOOK_KEY_LOCK "L - zablokuj"
#define HANDBOOK_KEY_MUTE "M - wycisz dzwiek"
#define HANDBOOK_KEY_OPTIONS "O - opcje"
#define HANDBOOK_KEY_SYNC "S - synchronizuj"
#define HANDBOOK_KEY_CREDITS "C - o programie"
#define HANDBOOK_KEY_RECONNECT "N - polacz Wi-Fi"

#define OPTIONS_DEFAULT_USERNAME "Domyslnie wprowadz: nazwe uzytkownika"
#define OPTIONS_DEFAULT_PASSWORD "Domyslnie wprowadz: haslo"
#define OPTIONS_DEFAULT_FULL "Domyslnie wprowadz: wszystko"
#define OPTIONS_SSID "SSID Wi-Fi: "
#define OPTIONS_WIFI_PASSWORD "Haslo Wi-Fi: "
#define OPTIONS_SYNC_HOST "Host synchr.: "
#define OPTIONS_SYNC_PORT "Port synchr.: "
#define OPTIONS_DEVICE_PASSWORD "Haslo glowne: "
#define OPTIONS_WIFI_OFF "Przedaw. proby polacz. Wi-Fi wylaczone"
#define OPTIONS_WIFI_TIMEOUT "Przedawnienie proby polaczenia: "
#define OPTIONS_WIFI_TIMEOUT_SECONDS_SHORTCUT " s"
#define OPTIONS_RTC_TIME "Czas RTC: "
#define OPTIONS_RTC_NTPSYNC " | Sync. z NTP"
#define OPTIONS_RTC_NTPSYNC_RTC_UNAVAILABLE "Sync. niedostepna: Brak RTC"
#define OPTIONS_EXPORT_VAULT "ENTER: eksportuj sejf na karte pamieci"

#define SYNC_WIFI_CONNECTING_PHASE "Laczenie z Wi-Fi"
#define SYNC_SERVER_CONNECTING_PHASE "Laczenie z serwerem"
#define SYNC_DOWNLOAD_PHASE "Pobieranie danych"
#define SYNC_OK "Synchr. OK, rozlaczanie"
#define SYNC_RETURN "Powrot za 3 sekundy"
#define SYNC_ERR "Blad synchronizacji:"
#define SYNC_ERR_DESCRIPTION_WIFI "Problem z Wi-Fi"
#define SYNC_ERR_DESCRIPTION_SERVER "Problem z serwerem"
#define SYNC_ERR_DESCRIPTION_FILE "Problem z plikiem"

#define CREDITS_PWDER "PWDer 0.5 \"Untangled\" >"
#define CREDITS_WEBSITE "< Zobacz moja strone! >"
#define CREDITS_PWDER_GITHUB "adamecki/PWDer na GitHub"
#define CREDITS_WEBSITE_LINK "floriano.uk"

#define PWIMPORT_REPLACE_PASSWORDS "Zastapic obecne hasla?"

#define SEARCH_NO_RESULTS "Brak wynikow"

#define SDCARD_NOT_FOUND_TITLE "Blad"
#define SDCARD_NOT_FOUND_DESCRIPTION "Nie znaleziono karty SD!"

#define SAMPLE_ENTRY "Przykladowy wpis"
#define SAMPLE_USERNAME "przykladowa_nazwa_uzytkownika"
#define SAMPLE_PASSWORD "przykladowe_haslo"
#endif
